### ISSUE TITLE
Ask for help. Thank you

### ISSUE THREAD

**Issue by shihuajin111** [DonggeunYu/MEV-Attack-on-the-BSC#3]
dex_infos = get_dex_infos_from_pool_list(pool_list_by_dex)
    dex_infos = set_token_addresses_to_dex_infos(cfg.http_endpoint, dex_infos)

I see that dex_infos is updated here, but I can't find a place to use it later, thanks

**Comment by DonggeunYu** [comment]
Yes, it is normal that you cannot find it. That function is code that was discarded during development. Not used.
At first, i wanted to collect all dex pool addresses and observe them. However, I found out that I just need to extract the pool address from the transaction.
